### PR TITLE
chore(logger): Add logger instead of print statements

### PR DESCRIPTION
**Pull request by iamanjali1003**
Fixes: #7

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
I was thinking of rather using uber's zap logger

**Review by shivamsouravjha — APPROVED** [review]
LGTM!

**Comment by iamanjali1003** [comment]
@shivamsouravjha, can you add the Hacktoberfest tag and also assign the issue to me so that I can keep it for reference?

**Comment by shivamsouravjha** [comment]
please comment on the issue

**Pull request merged**
